version: "3.8" # Docker Compose dosya sürümü

services:
  app: # Go uygulaman için servis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: messaging
      REDIS_HOST: redis
      REDIS_PORT: 6379

  postgres: # PostgreSQL servisi
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: messaging
    ports:
      - "5432:5432"

  redis: # Redis servisi
    image: redis:7
    ports:
      - "6379:6379"
